// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1tZXNzYWdlLnByb3RvGgxub3RpZnkucHJvdG8aDXJlcXVlc3QucHJvdG8a",
          "DnJlc3BvbnNlLnByb3RvGg1tc2dlbnVtLnByb3RvIoYBCghHTWVzc2FnZRIa",
          "Cgdtc2dUeXBlGAEgASgOMgkuTVNHX1RZUEUSDQoFc2VxSWQYAiABKAUSFwoG",
          "bm90aWZ5GAMgASgLMgcuTm90aWZ5EhkKB3JlcXVlc3QYBCABKAsyCC5SZXF1",
          "ZXN0EhsKCHJlc3BvbnNlGAUgASgLMgkuUmVzcG9uc2ViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::NotifyReflection.Descriptor, global::RequestReflection.Descriptor, global::ResponseReflection.Descriptor, global::MsgenumReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GMessage), global::GMessage.Parser, new[]{ "MsgType", "SeqId", "Notify", "Request", "Response" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GMessage : pb::IMessage<GMessage> {
  private static readonly pb::MessageParser<GMessage> _parser = new pb::MessageParser<GMessage>(() => new GMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<GMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GMessage(GMessage other) : this() {
    msgType_ = other.msgType_;
    seqId_ = other.seqId_;
    notify_ = other.notify_ != null ? other.notify_.Clone() : null;
    request_ = other.request_ != null ? other.request_.Clone() : null;
    response_ = other.response_ != null ? other.response_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GMessage Clone() {
    return new GMessage(this);
  }

  /// <summary>Field number for the "msgType" field.</summary>
  public const int MsgTypeFieldNumber = 1;
  private global::MSG_TYPE msgType_ = global::MSG_TYPE.Notify;
  /// <summary>
  ///消息类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::MSG_TYPE MsgType {
    get { return msgType_; }
    set {
      msgType_ = value;
    }
  }

  /// <summary>Field number for the "seqId" field.</summary>
  public const int SeqIdFieldNumber = 2;
  private int seqId_;
  /// <summary>
  ///消息的编号
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int SeqId {
    get { return seqId_; }
    set {
      seqId_ = value;
    }
  }

  /// <summary>Field number for the "notify" field.</summary>
  public const int NotifyFieldNumber = 3;
  private global::Notify notify_;
  /// <summary>
  ///通知类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Notify Notify {
    get { return notify_; }
    set {
      notify_ = value;
    }
  }

  /// <summary>Field number for the "request" field.</summary>
  public const int RequestFieldNumber = 4;
  private global::Request request_;
  /// <summary>
  ///请求类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Request Request {
    get { return request_; }
    set {
      request_ = value;
    }
  }

  /// <summary>Field number for the "response" field.</summary>
  public const int ResponseFieldNumber = 5;
  private global::Response response_;
  /// <summary>
  ///答复类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Response Response {
    get { return response_; }
    set {
      response_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as GMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(GMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MsgType != other.MsgType) return false;
    if (SeqId != other.SeqId) return false;
    if (!object.Equals(Notify, other.Notify)) return false;
    if (!object.Equals(Request, other.Request)) return false;
    if (!object.Equals(Response, other.Response)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (MsgType != global::MSG_TYPE.Notify) hash ^= MsgType.GetHashCode();
    if (SeqId != 0) hash ^= SeqId.GetHashCode();
    if (notify_ != null) hash ^= Notify.GetHashCode();
    if (request_ != null) hash ^= Request.GetHashCode();
    if (response_ != null) hash ^= Response.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (MsgType != global::MSG_TYPE.Notify) {
      output.WriteRawTag(8);
      output.WriteEnum((int) MsgType);
    }
    if (SeqId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(SeqId);
    }
    if (notify_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Notify);
    }
    if (request_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Request);
    }
    if (response_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Response);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (MsgType != global::MSG_TYPE.Notify) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
    }
    if (SeqId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeqId);
    }
    if (notify_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Notify);
    }
    if (request_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
    }
    if (response_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(GMessage other) {
    if (other == null) {
      return;
    }
    if (other.MsgType != global::MSG_TYPE.Notify) {
      MsgType = other.MsgType;
    }
    if (other.SeqId != 0) {
      SeqId = other.SeqId;
    }
    if (other.notify_ != null) {
      if (notify_ == null) {
        Notify = new global::Notify();
      }
      Notify.MergeFrom(other.Notify);
    }
    if (other.request_ != null) {
      if (request_ == null) {
        Request = new global::Request();
      }
      Request.MergeFrom(other.Request);
    }
    if (other.response_ != null) {
      if (response_ == null) {
        Response = new global::Response();
      }
      Response.MergeFrom(other.Response);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MsgType = (global::MSG_TYPE) input.ReadEnum();
          break;
        }
        case 16: {
          SeqId = input.ReadInt32();
          break;
        }
        case 26: {
          if (notify_ == null) {
            Notify = new global::Notify();
          }
          input.ReadMessage(Notify);
          break;
        }
        case 34: {
          if (request_ == null) {
            Request = new global::Request();
          }
          input.ReadMessage(Request);
          break;
        }
        case 42: {
          if (response_ == null) {
            Response = new global::Response();
          }
          input.ReadMessage(Response);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
