// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msgenum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from msgenum.proto</summary>
public static partial class MsgenumReflection {

  #region Descriptor
  /// <summary>File descriptor for msgenum.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MsgenumReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1tc2dlbnVtLnByb3RvKjEKCE1TR19UWVBFEgoKBk5PVElGWRAAEgsKB1JF",
          "UVVFU1QQARIMCghSRVNQT05TRRACKjEKC0hFUk9fU1RBVFVTEggKBExJVkUQ",
          "ABIICgRERUFEEAESDgoKSU5WSU5DSUJMRRACKjQKCkVWRU5UX1RZUEUSEgoO",
          "SEVST19DT0xMSVNJT04QABISCg5JVEVNX0NPTExJU0lPThABKjoKC0VOVElU",
          "WV9UWVBFEg0KCUhFUk9fVFlQRRAAEg0KCVBST1BfVFlQRRABEg0KCUZPT0Rf",
          "VFlQRRACKiQKC1JFU1VMVF9UWVBFEgsKB1NVQ0NFU1MQABIICgRGQUlMEAFi",
          "BnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MSG_TYPE), typeof(global::HERO_STATUS), typeof(global::EVENT_TYPE), typeof(global::ENTITY_TYPE), typeof(global::RESULT_TYPE), }, null, null));
  }
  #endregion

}
#region Enums
public enum MSG_TYPE {
  /// <summary>
  ///通知类型
  /// </summary>
  [pbr::OriginalName("NOTIFY")] Notify = 0,
  /// <summary>
  ///请求类型
  /// </summary>
  [pbr::OriginalName("REQUEST")] Request = 1,
  /// <summary>
  ///答复类型
  /// </summary>
  [pbr::OriginalName("RESPONSE")] Response = 2,
}

public enum HERO_STATUS {
  /// <summary>
  ///存活
  /// </summary>
  [pbr::OriginalName("LIVE")] Live = 0,
  /// <summary>
  ///死亡
  /// </summary>
  [pbr::OriginalName("DEAD")] Dead = 1,
  /// <summary>
  ///暂时无敌
  /// </summary>
  [pbr::OriginalName("INVINCIBLE")] Invincible = 2,
}

/// <summary>
/// eventType的枚举 
/// </summary>
public enum EVENT_TYPE {
  /// <summary>
  ///玩家碰撞事件
  /// </summary>
  [pbr::OriginalName("HERO_COLLISION")] HeroCollision = 0,
  /// <summary>
  ///道具碰撞事件
  /// </summary>
  [pbr::OriginalName("ITEM_COLLISION")] ItemCollision = 1,
}

/// <summary>
/// entityType的枚举 
/// </summary>
public enum ENTITY_TYPE {
  /// <summary>
  ///Hero类型
  /// </summary>
  [pbr::OriginalName("HERO_TYPE")] HeroType = 0,
  /// <summary>
  ///Prop类型--道具
  /// </summary>
  [pbr::OriginalName("PROP_TYPE")] PropType = 1,
  /// <summary>
  ///Food类型--食物
  /// </summary>
  [pbr::OriginalName("FOOD_TYPE")] FoodType = 2,
}

/// <summary>
/// response的result枚举 
/// </summary>
public enum RESULT_TYPE {
  /// <summary>
  ///成功
  /// </summary>
  [pbr::OriginalName("SUCCESS")] Success = 0,
  /// <summary>
  ///失败
  /// </summary>
  [pbr::OriginalName("FAIL")] Fail = 1,
}

#endregion


#endregion Designer generated code
