// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from request.proto</summary>
public static partial class RequestReflection {

  #region Descriptor
  /// <summary>File descriptor for request.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RequestReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1yZXF1ZXN0LnByb3RvGg1tc2dlbnVtLnByb3RvGgxzdHJ1Y3QucHJvdG8i",
          "awoHUmVxdWVzdBI1ChNlbnRpdHlDaGFuZ2VSZXF1ZXN0GAEgASgLMhguRW50",
          "aXR5SW5mb0NoYW5nZVJlcXVlc3QSKQoPaGVyb1F1aXRSZXF1ZXN0GAIgASgL",
          "MhAuSGVyb1F1aXRSZXF1ZXN0Io4BChdFbnRpdHlJbmZvQ2hhbmdlUmVxdWVz",
          "dBIeCglldmVudFR5cGUYASABKA4yCy5FVkVOVF9UWVBFEhAKCHBsYXllcklk",
          "GAIgASgFEhAKCGxpbmtlZElkGAMgASgFEhIKCmxpbmtlZFR5cGUYBCABKAUS",
          "GwoJcGxheWVyTXNnGAUgASgLMgguSGVyb01zZyIvCg9IZXJvUXVpdFJlcXVl",
          "c3QSDgoGaGVyb0lkGAEgASgFEgwKBHRpbWUYAiABKANiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::MsgenumReflection.Descriptor, global::StructReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "EntityChangeRequest", "HeroQuitRequest" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityInfoChangeRequest), global::EntityInfoChangeRequest.Parser, new[]{ "EventType", "PlayerId", "LinkedId", "LinkedType", "PlayerMsg" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HeroQuitRequest), global::HeroQuitRequest.Parser, new[]{ "HeroId", "Time" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Request : pb::IMessage<Request> {
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RequestReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request(Request other) : this() {
    entityChangeRequest_ = other.entityChangeRequest_ != null ? other.entityChangeRequest_.Clone() : null;
    heroQuitRequest_ = other.heroQuitRequest_ != null ? other.heroQuitRequest_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "entityChangeRequest" field.</summary>
  public const int EntityChangeRequestFieldNumber = 1;
  private global::EntityInfoChangeRequest entityChangeRequest_;
  /// <summary>
  ///实体改变请求，例如两条蛇相撞的时候、蛇吃道具的时候要发此类请求
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::EntityInfoChangeRequest EntityChangeRequest {
    get { return entityChangeRequest_; }
    set {
      entityChangeRequest_ = value;
    }
  }

  /// <summary>Field number for the "heroQuitRequest" field.</summary>
  public const int HeroQuitRequestFieldNumber = 2;
  private global::HeroQuitRequest heroQuitRequest_;
  /// <summary>
  ///玩家退出请求
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::HeroQuitRequest HeroQuitRequest {
    get { return heroQuitRequest_; }
    set {
      heroQuitRequest_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(EntityChangeRequest, other.EntityChangeRequest)) return false;
    if (!object.Equals(HeroQuitRequest, other.HeroQuitRequest)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (entityChangeRequest_ != null) hash ^= EntityChangeRequest.GetHashCode();
    if (heroQuitRequest_ != null) hash ^= HeroQuitRequest.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (entityChangeRequest_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(EntityChangeRequest);
    }
    if (heroQuitRequest_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(HeroQuitRequest);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (entityChangeRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityChangeRequest);
    }
    if (heroQuitRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeroQuitRequest);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.entityChangeRequest_ != null) {
      if (entityChangeRequest_ == null) {
        EntityChangeRequest = new global::EntityInfoChangeRequest();
      }
      EntityChangeRequest.MergeFrom(other.EntityChangeRequest);
    }
    if (other.heroQuitRequest_ != null) {
      if (heroQuitRequest_ == null) {
        HeroQuitRequest = new global::HeroQuitRequest();
      }
      HeroQuitRequest.MergeFrom(other.HeroQuitRequest);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (entityChangeRequest_ == null) {
            EntityChangeRequest = new global::EntityInfoChangeRequest();
          }
          input.ReadMessage(EntityChangeRequest);
          break;
        }
        case 18: {
          if (heroQuitRequest_ == null) {
            HeroQuitRequest = new global::HeroQuitRequest();
          }
          input.ReadMessage(HeroQuitRequest);
          break;
        }
      }
    }
  }

}

public sealed partial class EntityInfoChangeRequest : pb::IMessage<EntityInfoChangeRequest> {
  private static readonly pb::MessageParser<EntityInfoChangeRequest> _parser = new pb::MessageParser<EntityInfoChangeRequest>(() => new EntityInfoChangeRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<EntityInfoChangeRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RequestReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityInfoChangeRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityInfoChangeRequest(EntityInfoChangeRequest other) : this() {
    eventType_ = other.eventType_;
    playerId_ = other.playerId_;
    linkedId_ = other.linkedId_;
    linkedType_ = other.linkedType_;
    playerMsg_ = other.playerMsg_ != null ? other.playerMsg_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityInfoChangeRequest Clone() {
    return new EntityInfoChangeRequest(this);
  }

  /// <summary>Field number for the "eventType" field.</summary>
  public const int EventTypeFieldNumber = 1;
  private global::EVENT_TYPE eventType_ = global::EVENT_TYPE.HeroCollision;
  /// <summary>
  /// 事件类型 enum
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::EVENT_TYPE EventType {
    get { return eventType_; }
    set {
      eventType_ = value;
    }
  }

  /// <summary>Field number for the "playerId" field.</summary>
  public const int PlayerIdFieldNumber = 2;
  private int playerId_;
  /// <summary>
  /// 发送请求的实体Id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PlayerId {
    get { return playerId_; }
    set {
      playerId_ = value;
    }
  }

  /// <summary>Field number for the "linkedId" field.</summary>
  public const int LinkedIdFieldNumber = 3;
  private int linkedId_;
  /// <summary>
  /// 交互对象
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int LinkedId {
    get { return linkedId_; }
    set {
      linkedId_ = value;
    }
  }

  /// <summary>Field number for the "linkedType" field.</summary>
  public const int LinkedTypeFieldNumber = 4;
  private int linkedType_;
  /// <summary>
  ///交互的对象类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int LinkedType {
    get { return linkedType_; }
    set {
      linkedType_ = value;
    }
  }

  /// <summary>Field number for the "playerMsg" field.</summary>
  public const int PlayerMsgFieldNumber = 5;
  private global::HeroMsg playerMsg_;
  /// <summary>
  ///玩家的信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::HeroMsg PlayerMsg {
    get { return playerMsg_; }
    set {
      playerMsg_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as EntityInfoChangeRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(EntityInfoChangeRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EventType != other.EventType) return false;
    if (PlayerId != other.PlayerId) return false;
    if (LinkedId != other.LinkedId) return false;
    if (LinkedType != other.LinkedType) return false;
    if (!object.Equals(PlayerMsg, other.PlayerMsg)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (EventType != global::EVENT_TYPE.HeroCollision) hash ^= EventType.GetHashCode();
    if (PlayerId != 0) hash ^= PlayerId.GetHashCode();
    if (LinkedId != 0) hash ^= LinkedId.GetHashCode();
    if (LinkedType != 0) hash ^= LinkedType.GetHashCode();
    if (playerMsg_ != null) hash ^= PlayerMsg.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (EventType != global::EVENT_TYPE.HeroCollision) {
      output.WriteRawTag(8);
      output.WriteEnum((int) EventType);
    }
    if (PlayerId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PlayerId);
    }
    if (LinkedId != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(LinkedId);
    }
    if (LinkedType != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(LinkedType);
    }
    if (playerMsg_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(PlayerMsg);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (EventType != global::EVENT_TYPE.HeroCollision) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
    }
    if (PlayerId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
    }
    if (LinkedId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LinkedId);
    }
    if (LinkedType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LinkedType);
    }
    if (playerMsg_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerMsg);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(EntityInfoChangeRequest other) {
    if (other == null) {
      return;
    }
    if (other.EventType != global::EVENT_TYPE.HeroCollision) {
      EventType = other.EventType;
    }
    if (other.PlayerId != 0) {
      PlayerId = other.PlayerId;
    }
    if (other.LinkedId != 0) {
      LinkedId = other.LinkedId;
    }
    if (other.LinkedType != 0) {
      LinkedType = other.LinkedType;
    }
    if (other.playerMsg_ != null) {
      if (playerMsg_ == null) {
        PlayerMsg = new global::HeroMsg();
      }
      PlayerMsg.MergeFrom(other.PlayerMsg);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EventType = (global::EVENT_TYPE) input.ReadEnum();
          break;
        }
        case 16: {
          PlayerId = input.ReadInt32();
          break;
        }
        case 24: {
          LinkedId = input.ReadInt32();
          break;
        }
        case 32: {
          LinkedType = input.ReadInt32();
          break;
        }
        case 42: {
          if (playerMsg_ == null) {
            PlayerMsg = new global::HeroMsg();
          }
          input.ReadMessage(PlayerMsg);
          break;
        }
      }
    }
  }

}

public sealed partial class HeroQuitRequest : pb::IMessage<HeroQuitRequest> {
  private static readonly pb::MessageParser<HeroQuitRequest> _parser = new pb::MessageParser<HeroQuitRequest>(() => new HeroQuitRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HeroQuitRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RequestReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HeroQuitRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HeroQuitRequest(HeroQuitRequest other) : this() {
    heroId_ = other.heroId_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HeroQuitRequest Clone() {
    return new HeroQuitRequest(this);
  }

  /// <summary>Field number for the "heroId" field.</summary>
  public const int HeroIdFieldNumber = 1;
  private int heroId_;
  /// <summary>
  ///玩家Id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int HeroId {
    get { return heroId_; }
    set {
      heroId_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private long time_;
  /// <summary>
  ///离开时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HeroQuitRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HeroQuitRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (HeroId != other.HeroId) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HeroId != 0) hash ^= HeroId.GetHashCode();
    if (Time != 0L) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HeroId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(HeroId);
    }
    if (Time != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HeroId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(HeroId);
    }
    if (Time != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HeroQuitRequest other) {
    if (other == null) {
      return;
    }
    if (other.HeroId != 0) {
      HeroId = other.HeroId;
    }
    if (other.Time != 0L) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          HeroId = input.ReadInt32();
          break;
        }
        case 16: {
          Time = input.ReadInt64();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
