// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from response.proto</summary>
public static partial class ResponseReflection {

  #region Descriptor
  /// <summary>File descriptor for response.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResponseReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5yZXNwb25zZS5wcm90bxoNbXNnZW51bS5wcm90byJhCghSZXNwb25zZRIc",
          "CgZyZXN1bHQYASABKA4yDC5SRVNVTFRfVFlQRRI3ChRlbnRpdHlDaGFuZ2VS",
          "ZXNwb25zZRgCIAEoCzIZLkVudGl0eUluZm9DaGFuZ2VSZXNwb25zZSIwChhF",
          "bnRpdHlJbmZvQ2hhbmdlUmVzcG9uc2USFAoMY2hhbmdlUmVzdWx0GAEgASgI",
          "IigKEEhlcm9RdWl0UmVzcG9uc2USFAoMcXVpdFJlc3BvbnNlGAEgASgIYgZw",
          "cm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::MsgenumReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Result", "EntityChangeResponse" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityInfoChangeResponse), global::EntityInfoChangeResponse.Parser, new[]{ "ChangeResult" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HeroQuitResponse), global::HeroQuitResponse.Parser, new[]{ "QuitResponse" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Response : pb::IMessage<Response> {
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResponseReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response(Response other) : this() {
    result_ = other.result_;
    entityChangeResponse_ = other.entityChangeResponse_ != null ? other.entityChangeResponse_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::RESULT_TYPE result_ = global::RESULT_TYPE.Success;
  /// <summary>
  ///返回结果
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RESULT_TYPE Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "entityChangeResponse" field.</summary>
  public const int EntityChangeResponseFieldNumber = 2;
  private global::EntityInfoChangeResponse entityChangeResponse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::EntityInfoChangeResponse EntityChangeResponse {
    get { return entityChangeResponse_; }
    set {
      entityChangeResponse_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Result != other.Result) return false;
    if (!object.Equals(EntityChangeResponse, other.EntityChangeResponse)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Result != global::RESULT_TYPE.Success) hash ^= Result.GetHashCode();
    if (entityChangeResponse_ != null) hash ^= EntityChangeResponse.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Result != global::RESULT_TYPE.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Result);
    }
    if (entityChangeResponse_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(EntityChangeResponse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Result != global::RESULT_TYPE.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
    }
    if (entityChangeResponse_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityChangeResponse);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    if (other.Result != global::RESULT_TYPE.Success) {
      Result = other.Result;
    }
    if (other.entityChangeResponse_ != null) {
      if (entityChangeResponse_ == null) {
        EntityChangeResponse = new global::EntityInfoChangeResponse();
      }
      EntityChangeResponse.MergeFrom(other.EntityChangeResponse);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Result = (global::RESULT_TYPE) input.ReadEnum();
          break;
        }
        case 18: {
          if (entityChangeResponse_ == null) {
            EntityChangeResponse = new global::EntityInfoChangeResponse();
          }
          input.ReadMessage(EntityChangeResponse);
          break;
        }
      }
    }
  }

}

public sealed partial class EntityInfoChangeResponse : pb::IMessage<EntityInfoChangeResponse> {
  private static readonly pb::MessageParser<EntityInfoChangeResponse> _parser = new pb::MessageParser<EntityInfoChangeResponse>(() => new EntityInfoChangeResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<EntityInfoChangeResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResponseReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityInfoChangeResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityInfoChangeResponse(EntityInfoChangeResponse other) : this() {
    changeResult_ = other.changeResult_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityInfoChangeResponse Clone() {
    return new EntityInfoChangeResponse(this);
  }

  /// <summary>Field number for the "changeResult" field.</summary>
  public const int ChangeResultFieldNumber = 1;
  private bool changeResult_;
  /// <summary>
  ///改变结果是否有效
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool ChangeResult {
    get { return changeResult_; }
    set {
      changeResult_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as EntityInfoChangeResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(EntityInfoChangeResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ChangeResult != other.ChangeResult) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ChangeResult != false) hash ^= ChangeResult.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ChangeResult != false) {
      output.WriteRawTag(8);
      output.WriteBool(ChangeResult);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ChangeResult != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(EntityInfoChangeResponse other) {
    if (other == null) {
      return;
    }
    if (other.ChangeResult != false) {
      ChangeResult = other.ChangeResult;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ChangeResult = input.ReadBool();
          break;
        }
      }
    }
  }

}

/// <summary>
///玩家退出通知
/// </summary>
public sealed partial class HeroQuitResponse : pb::IMessage<HeroQuitResponse> {
  private static readonly pb::MessageParser<HeroQuitResponse> _parser = new pb::MessageParser<HeroQuitResponse>(() => new HeroQuitResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HeroQuitResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResponseReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HeroQuitResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HeroQuitResponse(HeroQuitResponse other) : this() {
    quitResponse_ = other.quitResponse_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HeroQuitResponse Clone() {
    return new HeroQuitResponse(this);
  }

  /// <summary>Field number for the "quitResponse" field.</summary>
  public const int QuitResponseFieldNumber = 1;
  private bool quitResponse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool QuitResponse {
    get { return quitResponse_; }
    set {
      quitResponse_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HeroQuitResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HeroQuitResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (QuitResponse != other.QuitResponse) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (QuitResponse != false) hash ^= QuitResponse.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (QuitResponse != false) {
      output.WriteRawTag(8);
      output.WriteBool(QuitResponse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (QuitResponse != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HeroQuitResponse other) {
    if (other == null) {
      return;
    }
    if (other.QuitResponse != false) {
      QuitResponse = other.QuitResponse;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          QuitResponse = input.ReadBool();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
